# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
    - job: Build Job1
      steps:
        - bash: echo $(Build.BuildNumber)

# - stage: DeployToDev
#   jobs:
#     - job: Build Job DeployToDev
#       steps:
#         - bash: echo $(Build.BuildNumber)
# - stage: DeployToQA
#   jobs:
#     - job: Build Job DeployToQA
#       steps:
#         - bash: echo $(Build.BuildNumber)
# - stage: DeployToProd
#   jobs:
#     - job: Build Job DeployToProd
#       steps:
#         - bash: echo $(Build.BuildNumber)



# steps:
# - task: Maven@3
#   inputs:
#     mavenPomFile: 'pom.xml'
#     mavenOptions: '-Xmx3072m'
#     javaHomeOption: 'JDKVersion'
#     jdkVersionOption: '1.8'
#     jdkArchitectureOption: 'x64'
#     publishJUnitResults: true
#     testResultsFiles: '**/surefire-reports/TEST-*.xml'
#     goals: 'package'
