jobs:
  - job: Build_Job1
    steps:
      - bash: echo $(Build.BuildNumber)
  - job: Build_Job2
    steps:
      - bash: echo $(Build.BuildNumber)
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          publishJUnitResults: false
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false